### ISSUE TITLE
Optimize The Code By Using 'mdo's Code Guide'

### ISSUE THREAD

**Issue by timderes** [derechtenap/xeon-eoh#19]
In order to write better code, I found this useful [Guide](https://codeguide.co/). It is created by mdo which is working on the Bootstrap Framework.

**Tasks**

- [x] Optimize the HTML syntax
- [x] Optimize the SCSS files
- [x] Setup an editor config
