### ISSUE TITLE
Fight Screen UI

### ISSUE THREAD

**Issue by timderes** [derechtenap/xeon-eoh#7]
![image](https://user-images.githubusercontent.com/50623315/96874348-503fff80-1476-11eb-85d5-9d5e3e855c7a.png)

**TODO**

- [x] Create HTML markup
- [x] Write SCSS Classes
- [x] Find an Color scheme

**Comment by timderes** [comment]
![Colors1](https://user-images.githubusercontent.com/50623315/96875197-3f43be00-1477-11eb-9fc8-ae8fe74eddd3.png)

**Comment by timderes** [comment]
![Colors2](https://user-images.githubusercontent.com/50623315/96875607-aeb9ad80-1477-11eb-9c57-d73bcb08014c.png)
![Colors3](https://user-images.githubusercontent.com/50623315/96875605-ae211700-1477-11eb-8543-a51c46b19582.png)
